name: 'Version Updater'
description: 'Update the version in a specified file based on the type of version bump'
inputs:
  file:
    description: 'Path to the file containing the version'
    required: true
  version-key:
    description: 'The key or pattern to identify the version in the file'
    required: true
    default: 'version'
  bump-type:
    description: 'The type of version bump: major, minor, or patch'
    required: true
    default: 'patch'
runs:
  using: 'node12'
  main: 'index.js'
