name: 'Semantic Versioning'
description: 'A GitHub Action for Semantic Versioning'
inputs:
  release_type:
    description: 'The type of release: major, minor, patch'
    required: true
outputs:
  new_version:
    description: 'The new version number'
runs:
  using: 'node12'
  main: 'index.js'
